/**
 * Pure content model: turns a content index (file list + frontmatter) into
 * routes, sidebar navigation, post lists and tags.
 *
 * Kept free of `virtual:novon/*` imports so it can be unit tested; `content.ts`
 * binds it to the generated index.
 */
import type { ComponentType } from 'react'
import type { Frontmatter, Route, RuntimeConfig, TocEntry } from '../types.ts'
import { humanize, tagSlug } from './lib.ts'

export interface PageModule {
  default: ComponentType<Record<string, unknown>>
  frontmatter?: Frontmatter
  headings?: TocEntry[]
}

/** File list and frontmatter of every page, as generated by the novon Vite plugin. */
export interface ContentIndex {
  files: string[]
  meta: Record<string, Frontmatter>
}

export interface NavPage {
  kind: 'page'
  label: string
  path: string
  order: number
  meta: Frontmatter
  /** From frontmatter, e.g. `icon: Rocket`. */
  icon?: string
}

export interface NavGroup {
  kind: 'group'
  label: string
  /** Link target when the group has its own `index.mdx`. */
  path?: string
  order: number
  children: NavNode[]
  /** From the group's index page frontmatter. */
  icon?: string
}

export type NavNode = NavPage | NavGroup

export interface SiteIndex {
  routes: Route[]
  byPath: Map<string, Route>
  /** Top-level sidebar/tree nodes. */
  nav: NavNode[]
  posts: Route[]
  tags: { tag: string; count: number }[]
}

/** `/content/guide/index.mdx` -> the `/guide` route. */
export function fileToRoute(file: string, meta: Frontmatter = {}): Route | undefined {
  const relative = file.replace(/^\/content\//, '').replace(/\.(md|mdx)$/, '')
  if (!relative) return undefined
  const raw = relative.split('/').filter(Boolean)
  if (raw.some((part) => part.startsWith('_'))) return undefined

  // Navigation follows the file tree; `slug` only changes the URL. Keeping these
  // separate means a slugged page stays in its sidebar group.
  const isIndex = raw[raw.length - 1] === 'index'
  const segments = isIndex ? raw.slice(0, -1) : raw

  let path = `/${segments.join('/')}`
  if (typeof meta.slug === 'string' && meta.slug.trim()) {
    path = `/${meta.slug.trim().replace(/^\/+|\/+$/g, '')}`
  }

  return {
    path: path === '/' ? '/' : path.replace(/\/+$/, ''),
    file,
    meta,
    segments,
    isIndex,
  }
}

function routeSortValue(route: Route): number {
  const order = route.meta.order
  return typeof order === 'number' ? order : 999
}

export function labelOf(route: Route): string {
  const { meta } = route
  if (typeof meta.label === 'string' && meta.label) return meta.label
  if (typeof meta.title === 'string' && meta.title) return meta.title
  const last = route.segments[route.segments.length - 1]
  return last ? humanize(last) : 'Home'
}

/** Build the route table from the content index. */
export function buildRoutes(
  template: 'docs' | 'blog' = 'docs',
  index: ContentIndex,
  isDev = false,
): Route[] {
  const routes: Route[] = []
  const seen = new Set<string>()

  for (const file of index.files) {
    const route = fileToRoute(file, index.meta[file] ?? {})
    if (!route) continue
    if (route.meta.draft === true && !isDev) continue
    if (seen.has(route.path)) {
      console.warn(`[novon] duplicate route ${route.path} (${file}) — keeping the first one`)
      continue
    }
    seen.add(route.path)
    routes.push(route)
  }

  routes.sort((a, b) => a.path.localeCompare(b.path))

  if (!routes.some((route) => route.path === '/')) {
    if (template === 'blog') {
      // A blog home is the post list, not the first post.
      routes.unshift({ path: '/', file: '', meta: {}, segments: [], isIndex: true, synthetic: true })
    } else {
      // Mirror mkdocs: `/` renders the first page when there is no `content/index.mdx`.
      const first = routes.find((route) => route.meta.sidebar !== false) ?? routes[0]
      routes.unshift(
        first
          ? { ...first, path: '/', segments: [], isIndex: true, synthetic: true }
          : { path: '/', file: '', meta: {}, segments: [], isIndex: true, synthetic: true },
      )
    }
  }

  return routes
}

interface DirNode {
  name: string
  index?: Route
  dirs: Map<string, DirNode>
  pages: Route[]
}

function pageNode(route: Route): NavPage {
  return {
    kind: 'page',
    label: labelOf(route),
    path: route.path,
    order: routeSortValue(route),
    meta: route.meta,
    icon: typeof route.meta.icon === 'string' ? route.meta.icon : undefined,
  }
}

function buildNavTree(routes: Route[]): NavNode[] {
  const root: DirNode = { name: '', dirs: new Map(), pages: [] }

  for (const route of routes) {
    if (route.synthetic || route.meta.sidebar === false) continue
    // For an index page `segments` is already the directory it labels.
    const dir = route.isIndex ? route.segments : route.segments.slice(0, -1)
    let node = root
    for (const name of dir) {
      let next = node.dirs.get(name)
      if (!next) {
        next = { name, dirs: new Map(), pages: [] }
        node.dirs.set(name, next)
      }
      node = next
    }
    if (route.isIndex) node.index = route
    else node.pages.push(route)
  }

  const toNodes = (node: DirNode): NavNode[] => {
    const pages: NavNode[] = node.pages
      .slice()
      .sort((a, b) => routeSortValue(a) - routeSortValue(b) || labelOf(a).localeCompare(labelOf(b)))
      .map(pageNode)

    const groups: NavGroup[] = [...node.dirs.values()].map((dir) => ({
      kind: 'group' as const,
      // The directory names the section; its `index.mdx` is listed as an item, so
      // a folder and its overview page never show the same label twice.
      label: humanize(dir.name),
      path: dir.index?.path,
      order: dir.index ? routeSortValue(dir.index) : 999,
      children: dir.index ? [pageNode(dir.index), ...toNodes(dir)] : toNodes(dir),
      icon: dir.index && typeof dir.index.meta.icon === 'string' ? dir.index.meta.icon : undefined,
    }))

    return [...pages, ...groups].sort((a, b) => a.order - b.order || a.label.localeCompare(b.label))
  }

  const nodes = toNodes(root)

  // The root `index.mdx` is a page, not a group label, so list it first.
  const home = root.index
  if (home && home.meta.sidebar !== false) {
    nodes.unshift({ ...pageNode(home), order: typeof home.meta.order === 'number' ? home.meta.order : -1 })
  }

  return nodes
}

function collectPosts(routes: Route[]): Route[] {
  return routes
    .filter((route) => !route.isIndex && !route.synthetic && route.meta.sidebar !== false)
    .sort((a, b) => {
      const dateA = a.meta.date ? Date.parse(String(a.meta.date)) : Number.NaN
      const dateB = b.meta.date ? Date.parse(String(b.meta.date)) : Number.NaN
      if (!Number.isNaN(dateA) && !Number.isNaN(dateB) && dateA !== dateB) return dateB - dateA
      if (!Number.isNaN(dateA) !== !Number.isNaN(dateB)) return Number.isNaN(dateA) ? 1 : -1
      return labelOf(a).localeCompare(labelOf(b))
    })
}

function collectTags(posts: Route[]): { tag: string; count: number }[] {
  const counts = new Map<string, number>()
  for (const post of posts) {
    const tags = Array.isArray(post.meta.tags) ? post.meta.tags : []
    for (const tag of tags) {
      if (typeof tag !== 'string' || !tag) continue
      counts.set(tag, (counts.get(tag) ?? 0) + 1)
    }
  }
  return [...counts.entries()]
    .map(([tag, count]) => ({ tag, count }))
    .sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag))
}

export function createSiteIndex(
  config: Pick<RuntimeConfig, 'template'>,
  index: ContentIndex,
  isDev = false,
): SiteIndex {
  const routes = buildRoutes(config.template, index, isDev)
  const byPath = new Map(routes.map((route) => [route.path, route]))
  const posts = collectPosts(routes)
  const tags = collectTags(posts)

  // Tag pages only make sense where a post list is the main navigation.
  if (config.template === 'blog') {
    if (!byPath.has('/blog')) {
      const route: Route = {
        path: '/blog',
        file: '',
        meta: { title: 'Blog' },
        segments: ['blog'],
        isIndex: false,
        synthetic: true,
        postList: true,
      }
      routes.push(route)
      byPath.set(route.path, route)
    }

    for (const { tag } of tags) {
      const path = `/tags/${tagSlug(tag)}`
      if (byPath.has(path)) continue
      const route: Route = {
        path,
        file: '',
        meta: { title: tag },
        segments: ['tags', tagSlug(tag)],
        isIndex: false,
        synthetic: true,
        tag,
      }
      routes.push(route)
      byPath.set(path, route)
    }
  }

  return { routes, byPath, nav: buildNavTree(routes), posts, tags }
}

export interface PageLink {
  label: string
  path: string
}

/** Flatten the tree so "previous / next" follows the sidebar order. */
export function flattenNav(nav: NavNode[]): PageLink[] {
  const out: PageLink[] = []
  const walk = (nodes: NavNode[]) => {
    for (const node of nodes) {
      if (node.kind === 'page') out.push({ label: node.label, path: node.path })
      else {
        if (node.path) out.push({ label: node.label, path: node.path })
        walk(node.children)
      }
    }
  }
  walk(nav)
  return out
}
