/**
 * Client-side search over `search-index.json`, generated by the `search` plugin.
 * The index is fetched the first time the palette opens.
 */
import * as React from 'react'
import { Search as SearchIcon } from 'lucide-react'
import { cn, withBase } from './lib.ts'
import { useBase, useConfig } from './site.tsx'
import { Dialog, DialogContent, Kbd } from './ui.tsx'
import { pageFrontmatter, routePathOf } from './content.ts'

interface SearchEntry {
  title: string
  path: string
  description?: string
  headings?: string[]
  text?: string
}

interface Scored extends SearchEntry {
  score: number
  snippet?: string
}

function scoreEntry(entry: SearchEntry, needle: string): Scored | undefined {
  const title = entry.title.toLowerCase()
  if (title.includes(needle)) return { ...entry, score: 100 }

  const heading = entry.headings?.find((item) => item.toLowerCase().includes(needle))
  if (heading) return { ...entry, score: 60, snippet: heading }

  const index = entry.text?.toLowerCase().indexOf(needle) ?? -1
  if (index >= 0) {
    const text = entry.text ?? ''
    const start = Math.max(0, index - 40)
    return { ...entry, score: 20, snippet: `…${text.slice(start, index + needle.length + 60)}…` }
  }
  return undefined
}

export function SearchTrigger({ className }: { className?: string }) {
  const config = useConfig()
  const base = useBase()
  const [open, setOpen] = React.useState(false)
  const [entries, setEntries] = React.useState<SearchEntry[] | null>(null)
  const [query, setQuery] = React.useState('')
  const [active, setActive] = React.useState(0)
  const inputRef = React.useRef<HTMLInputElement>(null)

  React.useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault()
        setOpen((value) => !value)
      }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [])

  React.useEffect(() => {
    if (!open || entries) return
    let cancelled = false
    // `novon dev` has no prerender step, so search uses frontmatter titles there
    // and the generated index everywhere else.
    const fallback = (): SearchEntry[] =>
      Object.entries(pageFrontmatter).map(([file, meta]) => ({
        title: String(meta?.label ?? meta?.title ?? file),
        path: routePathOf(file),
        description: typeof meta?.description === 'string' ? meta.description : undefined,
      }))

    if (import.meta.env.DEV) {
      setEntries(fallback())
      return
    }

    fetch(withBase(base, '/search-index.json'))
      .then((response) => (response.ok ? response.json() : fallback()))
      .then((data: SearchEntry[]) => {
        if (!cancelled) setEntries(Array.isArray(data) && data.length > 0 ? data : fallback())
      })
      .catch(() => {
        if (!cancelled) setEntries(fallback())
      })
    return () => {
      cancelled = true
    }
  }, [open, entries, base])

  React.useEffect(() => {
    if (open) window.setTimeout(() => inputRef.current?.focus(), 30)
    else {
      setQuery('')
      setActive(0)
    }
  }, [open])

  const results = React.useMemo<Scored[]>(() => {
    const needle = query.trim().toLowerCase()
    if (!needle) return (entries ?? []).slice(0, 8).map((entry) => ({ ...entry, score: 0 }))
    return (entries ?? [])
      .map((entry) => scoreEntry(entry, needle))
      .filter((entry): entry is Scored => Boolean(entry))
      .sort((a, b) => b.score - a.score || a.title.localeCompare(b.title))
      .slice(0, 12)
  }, [entries, query])

  const go = React.useCallback(
    (path: string) => {
      window.location.href = withBase(base, path)
    },
    [base],
  )

  const onKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      setActive((value) => Math.min(value + 1, results.length - 1))
    } else if (event.key === 'ArrowUp') {
      event.preventDefault()
      setActive((value) => Math.max(value - 1, 0))
    } else if (event.key === 'Enter' && results[active]) {
      event.preventDefault()
      go(results[active].path)
    }
  }

  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Search"
        className={cn(
          'inline-flex h-8 items-center gap-2 rounded-full border border-border bg-card/60 px-3 text-sm text-muted-foreground transition-colors hover:bg-accent hover:text-foreground sm:w-56',
          className,
        )}
      >
        <SearchIcon aria-hidden="true" className="size-4" />
        <span className="hidden flex-1 text-left sm:inline">Search</span>
        <Kbd className="hidden sm:inline-flex">⌘K</Kbd>
      </button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="p-0">
          <div className="flex items-center gap-2 border-b border-border px-4">
            <SearchIcon aria-hidden="true" className="size-4 shrink-0 text-muted-foreground" />
            <input
              ref={inputRef}
              value={query}
              onChange={(event) => {
                setQuery(event.target.value)
                setActive(0)
              }}
              onKeyDown={onKeyDown}
              placeholder={`Search ${config.title}…`}
              aria-label="Search documentation"
              className="h-12 w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground"
            />
          </div>

          <div className="max-h-[22rem] overflow-y-auto p-2">
            {entries === null ? (
              <p className="px-3 py-6 text-center text-sm text-muted-foreground">Loading…</p>
            ) : results.length === 0 ? (
              <p className="px-3 py-6 text-center text-sm text-muted-foreground">
                No results for “{query}”
              </p>
            ) : (
              <ul className="space-y-0.5">
                {results.map((entry, index) => (
                  <li key={`${entry.path}-${index}`}>
                    <a
                      href={withBase(base, entry.path)}
                      onMouseEnter={() => setActive(index)}
                      className={cn(
                        'block rounded-md px-3 py-2 text-sm no-underline',
                        index === active ? 'bg-accent text-accent-foreground' : 'text-foreground',
                      )}
                    >
                      <span className="block font-medium">{entry.title}</span>
                      {entry.snippet || entry.description ? (
                        <span className="mt-0.5 block truncate text-xs text-muted-foreground">
                          {entry.snippet ?? entry.description}
                        </span>
                      ) : null}
                    </a>
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div className="flex items-center justify-between border-t border-border px-4 py-2 text-xs text-muted-foreground">
            <span className="flex items-center gap-1">
              <Kbd>↑</Kbd>
              <Kbd>↓</Kbd> to navigate
            </span>
            <span className="flex items-center gap-1">
              <Kbd>↵</Kbd> to select
            </span>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
