/**
 * Client-side search over `search-index.json`, generated by the `search` plugin.
 * The index is fetched the first time the palette opens.
 */
import * as React from 'react'
import * as stylex from '@stylexjs/stylex'
import { Search as SearchIcon } from 'lucide-react'
import { colors, media, radii, space, type } from './design-system/tokens.stylex.ts'
import { typography } from './design-system/typography.ts'
import type { StyleXStyles } from '@stylexjs/stylex'
import { behavior } from './design-system/behaviors.ts'
import { withBase } from './lib.ts'
import { useBase, useConfig } from './site.tsx'
import { Dialog, DialogContent, Kbd } from './ui.tsx'
import { pageFrontmatter, routePathOf } from './content.ts'
import { navigate } from './navigation.ts'

interface SearchEntry {
  title: string
  path: string
  description?: string
  headings?: string[]
  text?: string
}

interface Scored extends SearchEntry {
  score: number
  snippet?: string
}

function scoreEntry(entry: SearchEntry, needle: string): Scored | undefined {
  const title = entry.title.toLowerCase()
  if (title.includes(needle)) return { ...entry, score: 100 }

  const heading = entry.headings?.find((item) => item.toLowerCase().includes(needle))
  if (heading) return { ...entry, score: 60, snippet: heading }

  const index = entry.text?.toLowerCase().indexOf(needle) ?? -1
  if (index >= 0) {
    const text = entry.text ?? ''
    const start = Math.max(0, index - 40)
    return { ...entry, score: 20, snippet: `…${text.slice(start, index + needle.length + 60)}…` }
  }
  return undefined
}

const styles = stylex.create({
  trigger: {
    display: 'inline-flex',
    height: space.eight,
    alignItems: 'center',
    gap: space.two,
    borderRadius: radii.control,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    backgroundColor: colors.surfaceRaised,
    paddingInline: space.three,
    color: colors.mutedText,
    cursor: 'pointer',
    transitionProperty: 'color, background-color',
    transitionDuration: '150ms',
    ':hover': { backgroundColor: colors.hover, color: colors.text },
  },
  triggerLabel: {
    flex: 1,
    textAlign: 'start',
    fontSize: type.label,
    lineHeight: type.compactLeading,
    display: { default: 'none', [media.small]: 'block' },
  },
  triggerKey: { display: { default: 'none', [media.small]: 'inline-flex' } },
  triggerCompact: {
    width: space.eight,
    padding: 0,
    justifyContent: 'center',
  },
  triggerCompactLabel: { display: 'none' },
  dialog: { padding: 0 },
  inputRow: {
    display: 'flex',
    alignItems: 'center',
    gap: space.two,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    paddingInline: space.four,
  },
  input: {
    height: space.twelve,
    width: '100%',
    backgroundColor: 'transparent',
    fontSize: type.label,
    lineHeight: type.compactLeading,
    borderWidth: 0,
    borderStyle: 'none',
    color: colors.text,
  },
  results: {
    maxHeight: '22rem',
    overflowY: 'auto',
    padding: space.two,
    display: 'flex',
    flexDirection: 'column',
    gap: space.half,
    listStyle: 'none',
    margin: 0,
  },
  status: {
    paddingInline: space.three,
    paddingBlock: space.six,
    textAlign: 'center',
    color: colors.mutedText,
  },
  result: {
    display: 'block',
    borderRadius: radii.control,
    paddingInline: space.three,
    paddingBlock: space.two,
    textDecoration: 'none',
    color: colors.text,
    backgroundColor: 'transparent',
  },
  resultActive: { backgroundColor: colors.hover },
  resultTitle: { display: 'block', fontWeight: type.medium },
  resultSnippet: {
    display: 'block',
    marginTop: space.half,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: colors.mutedText,
  },
  hints: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: colors.border,
    paddingInline: space.four,
    paddingBlock: space.two,
    color: colors.mutedText,
  },
  hint: { display: 'flex', alignItems: 'center', gap: space.one },
})

export function SearchTrigger({ xstyle, compact = false }: { xstyle?: StyleXStyles; compact?: boolean }) {
  const config = useConfig()
  const base = useBase()
  const [open, setOpen] = React.useState(false)
  const [entries, setEntries] = React.useState<SearchEntry[] | null>(null)
  const [query, setQuery] = React.useState('')
  const [active, setActive] = React.useState(0)
  const inputRef = React.useRef<HTMLInputElement>(null)
  const triggerRef = React.useRef<HTMLButtonElement>(null)

  React.useEffect(() => {
    const close = () => setOpen(false)
    window.addEventListener('novon:navigated', close)
    return () => window.removeEventListener('novon:navigated', close)
  }, [])

  React.useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (!event.defaultPrevented && triggerRef.current?.checkVisibility() && (event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
        event.preventDefault()
        setOpen((value) => !value)
      }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [])

  React.useEffect(() => {
    if (!open || entries) return
    let cancelled = false
    // `novon dev` has no prerender step, so search uses frontmatter titles there
    // and the generated index everywhere else.
    const fallback = (): SearchEntry[] =>
      Object.entries(pageFrontmatter).map(([file, meta]) => ({
        title: String(meta?.label ?? meta?.title ?? file),
        path: routePathOf(file),
        description: typeof meta?.description === 'string' ? meta.description : undefined,
      }))

    if (import.meta.env.DEV) {
      setEntries(fallback())
      return
    }

    fetch(withBase(base, '/search-index.json'))
      .then((response) => (response.ok ? response.json() : fallback()))
      .then((data: SearchEntry[]) => {
        if (!cancelled) setEntries(Array.isArray(data) && data.length > 0 ? data : fallback())
      })
      .catch(() => {
        if (!cancelled) setEntries(fallback())
      })
    return () => {
      cancelled = true
    }
  }, [open, entries, base])

  React.useEffect(() => {
    if (open) window.setTimeout(() => inputRef.current?.focus(), 30)
    else {
      setQuery('')
      setActive(0)
    }
  }, [open])

  const results = React.useMemo<Scored[]>(() => {
    const needle = query.trim().toLowerCase()
    if (!needle) return (entries ?? []).slice(0, 8).map((entry) => ({ ...entry, score: 0 }))
    return (entries ?? [])
      .map((entry) => scoreEntry(entry, needle))
      .filter((entry): entry is Scored => Boolean(entry))
      .sort((a, b) => b.score - a.score || a.title.localeCompare(b.title))
      .slice(0, 12)
  }, [entries, query])

  const go = React.useCallback(
    (path: string) => {
      setOpen(false)
      navigate(withBase(base, path))
    },
    [base],
  )

  const onKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      setActive((value) => Math.min(value + 1, results.length - 1))
    } else if (event.key === 'ArrowUp') {
      event.preventDefault()
      setActive((value) => Math.max(value - 1, 0))
    } else if (event.key === 'Enter' && results[active]) {
      event.preventDefault()
      go(results[active].path)
    }
  }

  return (
    <>
      <button
        ref={triggerRef}
        type="button"
        onClick={() => setOpen(true)}
        aria-label="Search"
        {...stylex.props(styles.trigger, compact && styles.triggerCompact, xstyle)}
      >
        <SearchIcon aria-hidden="true" size={16} />
        <span {...stylex.props(styles.triggerLabel, compact && styles.triggerCompactLabel)}>Search</span>
        <Kbd xstyle={styles.triggerKey}>⌘K</Kbd>
      </button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent aria-label="Search" xstyle={styles.dialog}>
          <div {...stylex.props(styles.inputRow)}>
            <SearchIcon aria-hidden="true" size={16} />
            <input
              ref={inputRef}
              value={query}
              onChange={(event) => {
                setQuery(event.target.value)
                setActive(0)
              }}
              onKeyDown={onKeyDown}
              placeholder={`Search ${config.title}…`}
              aria-label="Search documentation"
              {...stylex.props(styles.input)}
            />
          </div>

          <ul {...stylex.props(styles.results, behavior.scroll)}>
            {entries === null ? (
              <li {...stylex.props(styles.status, typography.labelRegular)}>Loading…</li>
            ) : results.length === 0 ? (
              <li {...stylex.props(styles.status, typography.labelRegular)}>
                No results for “{query}”
              </li>
            ) : (
              results.map((entry, index) => (
                <li key={`${entry.path}-${index}`}>
                  <a
                    href={withBase(base, entry.path)}
                    onMouseEnter={() => setActive(index)}
                    onClick={() => setOpen(false)}
                    {...stylex.props(styles.result, index === active && styles.resultActive)}
                  >
                    <span {...stylex.props(styles.resultTitle, typography.label)}>{entry.title}</span>
                    {entry.snippet || entry.description ? (
                      <span {...stylex.props(styles.resultSnippet, typography.captionRegular)}>
                        {entry.snippet ?? entry.description}
                      </span>
                    ) : null}
                  </a>
                </li>
              ))
            )}
          </ul>

          <div {...stylex.props(styles.hints, typography.captionRegular)}>
            <span {...stylex.props(styles.hint)}>
              <Kbd>↑</Kbd>
              <Kbd>↓</Kbd> to navigate
            </span>
            <span {...stylex.props(styles.hint)}>
              <Kbd>↵</Kbd> to select
            </span>
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}
