/**
 * Shared plumbing for the commands: locate the site, load its config, write the
 * generated Vite config shim and run Vite with Bun.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { findConfigFile, loadConfig, type ResolvedConfig } from '../config.ts'
import { cacheDir } from '../load.ts'
import type { NovonPlugin, PluginContext } from '../plugins/api.ts'
import { runtimeConfig } from '../vite-config.ts'

export interface Site {
  root: string
  packageRoot: string
  configFile: string
  config: ResolvedConfig
}

/** The vitest-style Vite config the CLI hands to `vite --config`. */
export function writeViteConfigShim(site: Site): string {
  const { root, packageRoot, configFile } = site
  const from = (path: string) => pathToFileURL(path).href
  const shim = join(cacheDir(root), 'vite.config.ts')
  const contents = `// Generated by novon. Safe to delete; recreated on every dev/build run.
import { importSiteModule } from ${JSON.stringify(from(join(packageRoot, 'src', 'load.ts')))}
import { normalizeBase, resolveConfig } from ${JSON.stringify(from(join(packageRoot, 'src', 'config.ts')))}
import { createNovonViteConfig } from ${JSON.stringify(from(join(packageRoot, 'src', 'vite-config.ts')))}

const siteRoot = ${JSON.stringify(root)}
const packageRoot = ${JSON.stringify(packageRoot)}
const configFile = ${JSON.stringify(configFile)}

const raw = await importSiteModule(configFile, packageRoot)
const config = resolveConfig(siteRoot, raw)

// CLI overrides (\`novon build --base … --out-dir …\`) have to reach this side of
// the build too, or prerendered links and emitted assets would disagree.
if (process.env.NOVON_BASE) config.base = normalizeBase(process.env.NOVON_BASE)
if (process.env.NOVON_OUT_DIR) config.outDir = process.env.NOVON_OUT_DIR

export default createNovonViteConfig({ packageRoot, siteRoot, configFile, config })
`
  // Vite watches its config file. Rewriting an unchanged shim restarts any dev
  // server for this site whenever another dev/build command starts.
  if (!existsSync(shim) || readFileSync(shim, 'utf8') !== contents) {
    writeFileSync(shim, contents)
  }
  return shim
}

export async function viteBin(packageRoot: string): Promise<string> {
  const candidates = [
    join(packageRoot, 'node_modules', 'vite', 'bin', 'vite.js'),
    join(packageRoot, '..', 'vite', 'bin', 'vite.js'),
  ]
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate
  }
  throw new Error(`[novon] could not find the vite CLI. Run \`bun install\` inside ${packageRoot}.`)
}

/** Run the Vite CLI under Bun, streaming output. */
export async function runVite(
  site: Site,
  args: string[],
  env: Record<string, string> = {},
): Promise<void> {
  const bin = await viteBin(site.packageRoot)
  const shim = writeViteConfigShim(site)
  const child = Bun.spawn(['bun', bin, ...args, '--config', shim, '--configLoader', 'native'], {
    cwd: site.root,
    env: { ...process.env, ...env },
    stdio: ['inherit', 'inherit', 'inherit'],
  })
  const code = await child.exited
  if (code !== 0) throw new Error(`vite exited with code ${code}`)
}

function pluginContext(site: Site): PluginContext {
  return {
    root: site.root,
    config: site.config,
    outDir: site.config.outDir,
    base: site.config.base,
    packageRoot: site.packageRoot,
  }
}

export async function runPluginSetup(plugins: NovonPlugin[], site: Site): Promise<void> {
  const context = pluginContext(site)
  for (const plugin of plugins) {
    await plugin.setup?.(context)
  }
}

export function ensureDir(path: string): void {
  if (!existsSync(path)) mkdirSync(path, { recursive: true })
}

export function writeFileEnsured(path: string, contents: string | Uint8Array): void {
  ensureDir(dirname(path))
  writeFileSync(path, contents)
}

/** Load the site: config + package locations. */
export async function loadSite(cwd: string, packageRoot: string): Promise<Site> {
  const root = resolve(cwd)
  const configFile = findConfigFile(root)
  const config = await loadConfig(root, packageRoot)
  return { root, packageRoot, configFile, config }
}

export { runtimeConfig }
